/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import java.awt.*;

import javax.swing.JFrame;

import controlador.Mandos;

/**
 *
 * @author carme
 */
public class Interfaz extends javax.swing.JFrame {

    Mandos mandos;
    Salpicadero salpicadero;
    /**
     * Creates new form Interfaz
     */
    public Interfaz(Mandos m, Salpicadero s) {
        mandos = m;
        salpicadero = s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.setLayout(new FlowLayout(FlowLayout.CENTER,10, 10));
        // this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setSize(new Dimension(1000,600));
        this.add(salpicadero);
        this.add(mandos);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
