/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.*;    
import javax.swing.*; 


import ejercicio4.Objetivo;

/**
 *
 * @author carme
 */
public class Salpicadero extends javax.swing.JPanel {
    public Objetivo objetivo;
    private CuentaKilometros distancia;
    private CuentaRevoluciones revoluciones;
    private Velocimetro velocidad;

    /**
     * Creates new form Salpicadero
     */
    public Salpicadero(Objetivo o) {
        this.objetivo = o;
        distancia = new CuentaKilometros(this);
        revoluciones = new CuentaRevoluciones(this);
        velocidad = new Velocimetro(this);
        initComponents();
    }

    public Objetivo getObjetivo() {
        return this.objetivo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    /*
     * private void initComponents() {
     * 
     * javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
     * this.setLayout(layout);
     * layout.setHorizontalGroup(
     * layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     * .addGap(0, 400, Short.MAX_VALUE));
     * layout.setVerticalGroup(
     * layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     * .addGap(0, 300, Short.MAX_VALUE));
     * }
     */// </editor-fold>//GEN-END:initComponents
       // private void initComponents() {
       // this.add(velocidad);
       // this.add(revoluciones);
       // this.add(distancia);
       // }

    private void initComponents() {
        this.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        this.add(distancia);
        this.add(revoluciones);
        this.add(velocidad);
    }

    public void actualizar(){
        distancia.actualizar();
        revoluciones.actualizar();
        velocidad.actualizar();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
